/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Bar: () => import('#controllers/bar_controller'),
  Floor: () => import('#controllers/floor_controller'),
  Kitchen: () => import('#controllers/kitchen_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Session: () => import('#controllers/session_controller'),
}
